/**
 * lib/supabase/database.types.ts — typed shape of the public schema.
 *
 * In a fuller implementation this file would be regenerated by:
 *
 *     npx supabase gen types typescript --project-id <ref> \
 *       --schema public > lib/supabase/database.types.ts
 *
 * Hand-rolled here so the initial commit doesn't require a running
 * Supabase CLI + DB round-trip. The shape mirrors
 * `supabase/migrations/0001_init_schema.sql` exactly — every table,
 * every column, every type. Update both together if you add a
 * column.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      food_categories: {
        Row: {
          id: string;
          slug: string;
          name: string;
          blurb: string;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          blurb: string;
          display_order: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["food_categories"]["Insert"]>;
        Relationships: [];
      };
      food_groups: {
        Row: {
          id: string;
          food_category_id: string;
          slug: string;
          name: string;
          display_order: number;
        };
        Insert: {
          id?: string;
          food_category_id: string;
          slug: string;
          name: string;
          display_order: number;
        };
        Update: Partial<Database["public"]["Tables"]["food_groups"]["Insert"]>;
        Relationships: [];
      };
      food_dishes: {
        Row: {
          id: string;
          food_group_id: string;
          name: string;
          price_half: number | null;
          price_full: number | null;
          price_single: number | null;
          note: string | null;
          on_request: boolean;
          is_featured: boolean;
          image_url: string | null;
          blur_data_url: string | null;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          food_group_id: string;
          name: string;
          price_half?: number | null;
          price_full?: number | null;
          price_single?: number | null;
          note?: string | null;
          on_request?: boolean;
          is_featured?: boolean;
          image_url?: string | null;
          blur_data_url?: string | null;
          display_order: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["food_dishes"]["Insert"]>;
        Relationships: [];
      };
      bar_categories: {
        Row: {
          id: string;
          slug: string;
          name: string;
          sizes: Json;
          display_order: number;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          sizes: Json;
          display_order: number;
        };
        Update: Partial<Database["public"]["Tables"]["bar_categories"]["Insert"]>;
        Relationships: [];
      };
      bar_pours: {
        Row: {
          id: string;
          bar_category_id: string;
          name: string;
          prices: Json;
          note: string | null;
          is_top_shelf: boolean;
          top_shelf_slot: number;
          image_url: string | null;
          blur_data_url: string | null;
          display_order: number;
        };
        Insert: {
          id?: string;
          bar_category_id: string;
          name: string;
          prices: Json;
          note?: string | null;
          is_top_shelf?: boolean;
          top_shelf_slot?: number;
          image_url?: string | null;
          blur_data_url?: string | null;
          display_order: number;
        };
        Update: Partial<Database["public"]["Tables"]["bar_pours"]["Insert"]>;
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          role: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          role?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
